apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduler
  namespace: oci-ods
spec:
  replicas: 1
  selector: { matchLabels: { app: scheduler } }
  template:
    metadata: { labels: { app: scheduler } }
    spec:
      containers:
        - name: scheduler
          image: ghcr.io/example/oci-ods-scheduler:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: REDIS_HOST
              value: redis
          volumeMounts:
            - name: manifests
              mountPath: /app/manifests
      volumes:
        - name: manifests
          configMap:
            name: ods-manifests
            items:
              - key: example-catalogue.yaml
                path: example-catalogue.yaml
