jobs:
  - name: list-buckets    
    oci_tenancy_name: "your_tenancy_name"
    oci_namespace: "your_namespace"
    oci_region: "uk-london-1"    
    frequency_minutes: 5

  - name: list-objects
    oci_tenancy_name: "your_tenancy_name"
    oci_namespace: "your_namespace"
    oci_region: "uk-london-1"
    frequency_minutes: 5